01:01:04 : Running on GPU 
01:01:04 : Model is Exp_7_TwoStream_Say_LF_SpatialFusion_b32e50L0.0001 
01:01:04 : No saved model found. Training a new model. 
01:01:08 : Error occured Dimension out of range (expected to be in range of [-2, 1], but got 2) 
01:01:08 : Traceback (most recent call last):
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 664, in <module>
    model = train_model(dataloader_train_raw, dataloader_val_raw,dataloader_train_OF, dataloader_val_OF, num_epochs,learning_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 432, in train_model
    outputs = model(batch_features1,batch_features2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 222, in forward
    fused_logits = torch.cat((logits1, logits2), dim=2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
 
01:01:08 : ****************************** 
01:10:13 : Running on GPU 
01:10:13 : Model is Exp_7_TwoStream_Say_LF_SpatialFusion_b32e50L0.0001 
01:10:13 : No saved model found. Training a new model. 
01:10:15 : Error occured Dimension out of range (expected to be in range of [-2, 1], but got 2) 
01:10:15 : Traceback (most recent call last):
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 679, in <module>
    model = train_model(dataloader_train_raw, dataloader_val_raw,dataloader_train_OF, dataloader_val_OF, num_epochs,learning_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 447, in train_model
    outputs = model(batch_features1,batch_features2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 237, in forward
    fused_logits = torch.cat((logits1, logits2), dim=2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
 
01:10:15 : ****************************** 
01:22:37 : Running on GPU 
01:22:37 : Model is Exp_7_TwoStream_Say_LF_SpatialFusion_b32e50L0.0001 
01:22:37 : No saved model found. Training a new model. 
01:22:39 : Error occured Dimension out of range (expected to be in range of [-2, 1], but got 2) 
01:22:39 : Traceback (most recent call last):
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 848, in <module>
    model = train_model(dataloader_train_raw, dataloader_val_raw,dataloader_train_OF, dataloader_val_OF, num_epochs,learning_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 616, in train_model
    outputs = model(batch_features1,batch_features2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 366, in forward
    fused_logits = torch.cat((logits1, logits2), dim=2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
 
01:22:39 : ****************************** 
15:08:45 : Running on GPU 
15:08:45 : Model is Exp_7_TwoStream_Say_LF_SpatialFusion_b32e50L0.0001 
15:08:45 : No saved model found. Training a new model. 
15:08:49 : Error occured Dimension out of range (expected to be in range of [-2, 1], but got 2) 
15:08:49 : Traceback (most recent call last):
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 857, in <module>
    model = train_model(dataloader_train_raw, dataloader_val_raw,dataloader_train_OF, dataloader_val_OF, num_epochs,learning_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 625, in train_model
    outputs = model(batch_features1,batch_features2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 375, in forward
    fused_logits = torch.cat((raw_Stream_out, OF_Stream_out), dim=2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
 
15:08:49 : ****************************** 
15:19:02 : Running on GPU 
15:19:02 : Model is Exp_7_TwoStream_Say_LF_SpatialFusion_b32e50L0.0001 
15:19:02 : No saved model found. Training a new model. 
15:19:04 : Error occured Dimension out of range (expected to be in range of [-2, 1], but got 2) 
15:19:04 : Traceback (most recent call last):
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 860, in <module>
    model = train_model(dataloader_train_raw, dataloader_val_raw,dataloader_train_OF, dataloader_val_OF, num_epochs,learning_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 628, in train_model
    outputs = model(batch_features1,batch_features2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 378, in forward
    fused_logits = torch.cat((raw_Stream_out, OF_Stream_out), dim=2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
 
15:19:04 : ****************************** 
15:21:39 : Running on GPU 
15:21:39 : Model is Exp_7_TwoStream_Say_LF_SpatialFusion_b32e50L0.0001 
15:21:39 : No saved model found. Training a new model. 
15:21:41 : Error occured Dimension out of range (expected to be in range of [-2, 1], but got 2) 
15:21:41 : Traceback (most recent call last):
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 860, in <module>
    model = train_model(dataloader_train_raw, dataloader_val_raw,dataloader_train_OF, dataloader_val_OF, num_epochs,learning_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 628, in train_model
    outputs = model(batch_features1,batch_features2)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\binso\anaconda3\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Cloud_drives\OneDrive - University of Hertfordshire\ProjectWorkables\MscProjectRepo\smt_repo\Exp_7_TwoStream_Say_LF_SpatialFusion.py", line 378, in forward
    fused_logits = torch.cat((raw_Stream_out, OF_Stream_out), dim=2)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)
 
15:21:41 : ****************************** 
